sequenceDiagram
    participant TaskManager
    participant UIController
    participant UploadAgent
    participant VcsLocalServer

    UIController ->> UploadAgent: Pass target filepath

    UploadAgent ->>+ VcsLocalServer: Check if {owner}/{repo} exists on local fs
    VcsLocalServer ->>- UploadAgent: repo status

    alt Repository not found
    UploadAgent ->>+ VcsLocalServer: /initialize/repository/appData/repos/{owner}/{repo}
    VcsLocalServer ->>- UploadAgent: Repository created
    end

    UploadAgent ->>+ VcsLocalServer: /{owner}/{repo}/ghost-stage?filepath=<wantedFile>
    VcsLocalServer ->>- UploadAgent: Branch to push to

    UploadAgent ->>+ VcsLocalServer: /{owner}/{repo}/switch/branch/{branch}?world-effects=false
    VcsLocalServer ->>- UploadAgent: Branch switched

    UploadAgent ->>+ VcsLocalServer: /{owner}/{repo}/commit
    VcsLocalServer ->>- UploadAgent: Commited successfully

    UploadAgent ->>+ VcsLocalServer: /{owner}/{repo}/push/{branch}
    VcsLocalServer ->>- UploadAgent: Push in process

    UploadAgent ->>+ VcsLocalServer: Establish web socket
    VcsLocalServer ->>- UploadAgent: Web socket established

    alt Streaming upload status via websocket

    VcsLocalServer -) UploadAgent: Upload State
    UploadAgent -) TaskManager: Update Upload State
    
    end

    alt Push is done
    UploadAgent ->>+ VcsLocalServer: /{owner}/{repo}/wash
    VcsLocalServer ->>- UploadAgent: Washed latest writes

    UploadAgent ->>+ VcsLocalServer: /copy?from={filepath}&to={owner}/{repo}/ready
    
    alt Copy is done
    VcsLocalServer ->> UploadAgent: Close Connection
    end

    end
    

    UIController --> TaskManager: Render task state
    